### ISSUE TITLE
потеряли draw()

### ISSUE THREAD

**Issue by Sild** [thedilletante/multi_snake#13]
`future: <Task finished coro=<Game.start() done, defined at /Users/sildtm/Projects/github_sild/snake_tournament/server/models/Game.py:23> exception=AttributeError("'StateHandler' object has no attribute 'draw'",)>
`

забыли в messages?

**Comment by thedilletante** [comment]
[`Поправлено`](https://github.com/thedilletante/multi_snake/commit/ae5e106b4aacbf89278396b9a057d5a85319cd97)
